---
- apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state: present
- apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
- apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
- apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - docker-engine
    - docker-compose
- user:
    name: ubuntu
    groups: docker
    append: yes
